variables:
  tfBackendStorageAccountName: project12345 
  tfBackendStorageContainerName: proj-java 
  tfBackendFileName: terraform.tfstate 
pool:
  vmImage: 'ubuntu-latest'
steps:

#KEY VAULT TASK
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'devops-sp'
    KeyVaultName: 'mykeyzvault'
    SecretsFilter: 'sp-clientid-tf-929,sp-secret-tf-929,sp-tenantid-tf-929,sp-subscriptionid-tf-929,ak-backend-sa-929'
  displayName: 'Get key vault secrets as pipeline variables'

# TERRAFORM VERSION
- script: |
    terraform version

# AZ LOGIN USING TERRAFORM SERVICE PRINCIPAL
- script: |
    az login --service-principal -u $(sp-clientid-tf-929) -p $(sp-secret-tf-929) --tenant $(sp-tenant-tf-929)
    # TERRAFORM INIT    
    echo '#######Terraform Init########'
    terraform init -backend-config="storage_account_name=$(tfBackendStorageAccountName)" -backend-config="container_name=$(tfBackendStorageContainerName)" -backend-config="access_key=$(ak-backend-sa-929)" -backend-config="key=$(tfBackendFileName)"
    # TERRAFORM PLAN    
    echo '#######Terraform Plan########'
    terraform plan -var="client-id=$(sp-clientid-tf-929)" -var="client-secret=$(sp-secret-tf-929)" -var="tenant-id=$(sp-tenant-tf-929)" -var="subscription-id=$(sp-subscriptionid-tf-929)" -out="out.plan"
    # TERRAFORM APPLY    
    echo '#######Terraform Apply########'
    terraform apply out.plan
  displayName: 'Terraform Init, Plan and Apply '
