variables:
  TF_STORAGE_ACCT_NAME: tfstateacct0733
  TF_STORAGE_CONT_NAME: proj-java 
  TF_STATE_FILE: terraform.tfstate 
pool:
  vmImage: 'ubuntu-latest'
steps:

#KEY VAULT TASK
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'devops-sp'
    KeyVaultName: 'mykeyzvault'
    SecretsFilter: 'sp-client-id-tf-0733,sp-cert-tf-0733,sp-tenant-id-tf-0733,sp-subscription-id-tf-0733,ak-backend-sa-0733'
  displayName: 'Get key vault secrets as pipeline variables'

# TERRAFORM VERSION
- script: |
    terraform version
  displayName: 'Get Terraform Version'

- script: |
    echo "$(sp-cert-tf-0733)" > service-principal.pfx.b64
    base64 --decode service-principal.pfx.b64 > service-principal.pfx
    openssl pkcs12 -in service-principal.pfx -out service-principal.pem -nodes -passin pass:
    cat service-principal.pem
    ls -la
  displayName: 'What is in the cert variable?'

# AZ LOGIN USING TERRAFORM SERVICE PRINCIPAL
- script: |
    az login --service-principal -u "$(sp-client-id-tf-0733)" -p "service-principal.pem" --tenant "$(sp-tenant-id-tf-0733)"
  displayName: 'Login the az cli'

- script: |
    cd iac
    echo '#######Terraform Init########'
    terraform init -backend-config="storage_account_name=$(TF_STORAGE_ACCT_NAME)" -backend-config="container_name=$(TF_STORAGE_CONT_NAME)" -backend-config="access_key=$(ak-backend-sa-0733)" -backend-config="key=$(TF_STATE_FILE)"
    echo '#######Terraform Plan########'
    terraform plan -var="clientId=$(sp-client-id-tf-0733)" -var="tenantId=$(sp-tenant-id-tf-0733)" -var="subscriptionId=$(sp-subscription-id-tf-0733)" -out="out.plan"
    echo '#######Terraform Apply########'
    terraform apply out.plan
  displayName: 'Terraform Init, Plan and Apply '
