variables:
  tfBackendStorageAccountName: project12345 
  tfBackendStorageContainerName: proj-java 
  tfBackendFileName: terraform.tfstate 
pool:
  vmImage: 'ubuntu-latest'
steps:

#KEY VAULT TASK
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'devops-sp'
    KeyVaultName: 'mykeyzvault'
    SecretsFilter: 'sp-clientid-tf-801,sp-secret-tf-801,sp-tenantid-tf-801,sp-subscriptionid-tf-801,ak-backend-sa-801'
  displayName: 'Get key vault secrets as pipeline variables'

# TERRAFORM VERSION
- script: |
    terraform version
  displayName: 'Get Terraform Version'

# AZ LOGIN USING TERRAFORM SERVICE PRINCIPAL
- script: |
    az login --service-principal -u "$(sp-clientid-tf-801)" -p "$(sp-secret-tf-801)" --tenant "$(sp-tenantid-tf-801)"
  displayName: 'Login the az cli'

- script: |
    # TERRAFORM INIT    
    echo '#######Terraform Init########'
    terraform init -backend-config="storage_account_name=$(tfBackendStorageAccountName)" -backend-config="container_name=$(tfBackendStorageContainerName)" -backend-config="access_key=$(ak-backend-sa-801)" -backend-config="key=$(tfBackendFileName)"
    # TERRAFORM PLAN    
    echo '#######Terraform Plan########'
    terraform plan -var="client-id=$(sp-clientid-tf-801)" -var="client-secret=$(sp-secret-tf-801)" -var="tenant-id=$(sp-tenantid-tf-801)" -var="subscription-id=$(sp-subscriptionid-tf-801)" -out="out.plan"
    # TERRAFORM APPLY    
    echo '#######Terraform Apply########'
    terraform apply out.plan
  displayName: 'Terraform Init, Plan and Apply '
